version: '3.8'

services:
  app:
    build: 
      context: .
      args:
        - NODE_ENV=production
    ports:
      - "80:3000"  # Expose only the backend port for production
    volumes:
      - ./server/database:/app/server/database
      - ./server/uploads:/app/server/uploads
    environment:
      - NODE_ENV=production
      - JWT_SECRET=your-secret-key
      - FRONTEND_URL=http://localhost
      - PORT=3000
      - TWILIO_ACCOUNT_SID=your-twilio-sid
      - TWILIO_AUTH_TOKEN=your-twilio-token
      - TWILIO_WHATSAPP_NUMBER=your-twilio-whatsapp
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3